# Generated by Django 3.2.5 on 2022-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='WarningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgBase', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
