# Generated by Django 3.2.5 on 2022-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning', '0002_auto_20220416_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushuser',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
