# Generated by Django 3.2.5 on 2022-06-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning', '0003_alter_pushuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushuser',
            name='enable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
