# Generated by Django 3.2.5 on 2022-06-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning', '0004_pushuser_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushuser',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
