# Generated by Django 3.2.5 on 2022-07-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning', '0005_alter_pushuser_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='warninghistory',
            name='type',
            field=models.CharField(default='三轮车识别', max_length=10, verbose_name='类型'),
            preserve_default=False,
        ),
    ]
