# Generated by Django 3.2.5 on 2022-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning', '0006_warninghistory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='warninghistory',
            name='bigImg',
            field=models.FileField(default='', upload_to='warning/', verbose_name='大图'),
            preserve_default=False,
        ),
    ]
