# Generated by Django 3.2.5 on 2022-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning', '0007_warninghistory_bigimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warninghistory',
            name='type',
            field=models.IntegerField(verbose_name='类型'),
        ),
    ]
