# Generated by Django 3.2.5 on 2022-07-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning', '0008_alter_warninghistory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environmental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('la', models.FloatField()),
            ],
        ),
    ]
